const { OpenAI } = require('openai');

// Initialize the OpenAI Client securely using server-side environment variables
const openai = new OpenAI({ 
  apiKey: process.env.OPENAI_API_KEY 
});
const ASSISTANT_ID = process.env.OPENAI_ASSISTANT_ID;

// In-Memory Rate Limiter to protect your tokens from abuse/spam loops
const ipCache = {};
setInterval(() => { 
  for (const ip in ipCache) {
    if (Date.now() > ipCache[ip].reset) delete ipCache[ip];
  }
}, 60000); // Clean cache every minute

module.exports = async (req, res) => {
  // Enforce global Cross-Origin Resource Sharing (CORS) so your Shopify frontend can talk to this file
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  // Handle pre-flight browser requests instantly without executing AI token workflows
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Enforce POST requests only
  if (req.method !== 'POST') {
    return res.status(405).json({ error: "method_not_allowed" });
  }

  // Capture user IP to calculate rate limits
  const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress || 'anonymous';
  const now = Date.now();

  if (!ipCache[ip]) {
    ipCache[ip] = { count: 0, reset: now + 3600000 }; // 1 hour sliding window
  }

  // Budget Protection Guardrail: Max 4 requests per hour per user IP address
  if (ipCache[ip].count >= 4) {
    return res.status(429).json({ 
      error: "rate_limit_exceeded", 
      message: "Session limit reached. Check matches above!" 
    });
  }

  const { text } = req.body;

  // Frontend Guardrail Double-Check: Stop empty inputs before spending tokens
  if (!text || text.trim().length < 3) {
    return res.status(400).json({ error: "bad_input" });
  }

  // Increment rate limiter count for this IP address
  ipCache[ip].count++;

  try {
    // 1. Create a secure, isolated communication thread with OpenAI
    const thread = await openai.beta.threads.create();

    // 2. Append the shopper's prompt query straight into the thread canvas
    await openai.beta.threads.messages.create(thread.id, { 
      role: "user", 
      content: text 
    });

    // 3. Command the Knowledge Assistant to scan the Shopify CSV and respond
    let run = await openai.beta.threads.runs.createAndPoll(thread.id, { 
      assistant_id: ASSISTANT_ID 
    });

    // 4. Extract, sanitize, and return the structured data object
    if (run.status === 'completed') {
      const messages = await openai.beta.threads.messages.list(thread.id);
      const rawOutput = messages.data[0].content[0].text.value;
      
      // Clean up markdown wrapper styling constraints if generated by the AI model
      const cleanJson = JSON.parse(rawOutput.replace(/```json|```/g, '').trim());
      
      return res.status(200).json(cleanJson);
    } else {
      return res.status(500).json({ error: "run_failed" });
    }

  } catch (err) {
    console.error("Gateway Processing Exception:", err);
    return res.status(500).json({ error: "server_error" });
  }
};