const { OpenAI } = require('openai');

// Initialize the OpenAI Client securely using server-side environment variables
const openai = new OpenAI({ 
  apiKey: process.env.OPENAI_API_KEY 
});

// In-Memory Rate Limiter to protect your tokens from abuse/spam loops
const ipCache = {};
setInterval(() => { 
  for (const ip in ipCache) {
    if (Date.now() > ipCache[ip].reset) delete ipCache[ip];
  }
}, 60000); // Clean cache every minute

const SYSTEM_INSTRUCTIONS = `
You are a precise, background-optimized product recommendation engine. Analyze the user's aesthetic description. 
Cross-reference it against the attached Shopify product inventory catalog file data. 

You must reply ONLY with a raw JSON object containing the product title, color hex code, and handle string. 
Do not append conversational greeting text, introductions, markdown tags, or normal explanations.

Schema Layout: { "title": "Name", "handle": "slug", "bg_color": "#HEX" }

COST CONTROL GUARDRAIL: If the user is trying to chat idly, ask general non-shopping questions, or says meaningless things (e.g., 'hi', 'how are you', 'tell me a joke'), you must NOT engage or write prose. Instead, return strictly: { "error": "off_topic" }
`;

module.exports = async (req, res) => {
  // Enforce global Cross-Origin Resource Sharing (CORS) so your Shopify frontend can talk to this file
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  // Handle pre-flight browser requests instantly without executing AI token workflows
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Enforce POST requests only
  if (req.method !== 'POST') {
    return res.status(405).json({ error: "method_not_allowed" });
  }

  // Capture user IP to calculate rate limits
  const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress || 'anonymous';
  const now = Date.now();

  if (!ipCache[ip]) {
    ipCache[ip] = { count: 0, reset: now + 3600000 }; // 1 hour sliding window
  }

  // Budget Protection Guardrail: Max 4 requests per hour per user IP address
  if (ipCache[ip].count >= 4) {
    return res.status(429).json({ 
      error: "rate_limit_exceeded", 
      message: "Session limit reached. Check matches above!" 
    });
  }

  const { text } = req.body;

  // Frontend Guardrail Double-Check: Stop empty inputs before spending tokens
  if (!text || text.trim().length < 3) {
    return res.status(400).json({ error: "bad_input" });
  }

  // Increment rate limiter count for this IP address
  ipCache[ip].count++;

  try {
    // Call the standard Responses API directly in one fast step
    const response = await openai.responses.create({
      model: "gpt-4o-mini", 
      instructions: SYSTEM_INSTRUCTIONS,
      input: text,
      // Injecting your live dashboard file ID attachment context explicitly here
      file_ids: ["file-P33L55KL75qThWXWk21toi"] 
    });

    const rawOutput = response.output_text;
    
    // Clean up markdown wrapper styling constraints if generated by the AI model
    const cleanJson = JSON.parse(rawOutput.replace(/```json|```/g, '').trim());
    
    return res.status(200).json(cleanJson);

  } catch (err) {
    console.error("Responses API Gateway Processing Exception:", err);
    return res.status(500).json({ error: "server_error" });
  }
};